### ISSUE TITLE
Recent actions showing in column instead of row

### ISSUE THREAD

**Issue by rockwallguy** [theripper93/Combat-Booster#1]
My friend and I both recently found your module and we like it, but we're having an issue where the recent actions are showing as a column like this:

![image](https://user-images.githubusercontent.com/79724010/127289073-6dc29fbd-ce4e-47f8-8fbd-c932f4f5204b.png)

Instead of in a row like it shows on the instructional page.  I ran Find the Culprit, and it looks like the cause is the TorchLight module.  I don't know if that's a thing you're interested in fixing or not, but I thought I'd let you know so at least you were aware of the issue.

**Comment by theripper93** [comment]
Torchlight changes the core css for no real reason, not really much I can do on my end, they are doing something that you should not do and causing issues for others

**Comment by theripper93** [comment]
That said it should fix itself when you have more than 2 icons (maybe)
