### ISSUE TITLE
Renaming Items causes Recent Actions to stop updating/not work

### ISSUE THREAD

**Issue by GambetTV** [theripper93/Combat-Booster#11]
If you rename an item, the (technically) old item stays in the Recent Actions list, but clicking on it gives you the popup: "Your controlled Actor does not have an item named _____". This is fine, but for some reason using the renamed item by going into your character sheet and clicking on it does not cause it to update the Recent Actions list. 

So for instance, if I change an item from the name Longsword to Greatsword, Longsword will remain in the Recent Actions list, and going into the sheet and clicking on Greatsword, even a bunch of times, will not cause the Recent Actions list to update with it. Other items will update it, but it even getting Longsword to eventually cycle off the list will not replace it with Greatsword ever.

**Comment by theripper93** [comment]
Combat booster does not use item names - those are only for rolling. the recent items are stored by ID so i'm not even sure what your issue is. It's not happening on my end. Did you follow the instructions and test with all other mods disabled?

**Comment by GambetTV** [comment]
Yes, I'm 100% certain no other modules are running and the error is still happening.

https://user-images.githubusercontent.com/72000497/152654737-a4be3df0-ff8f-4d95-b690-faef60ec187e.mp4

**Comment by Darshyne** [comment]
I have the same issue : attack with weapons are not showing up in the HUD

**Comment by theripper93** [comment]
made some changes that should fix these issues
