### ISSUE TITLE
Compatibility with DSA/TDE Lifepoints

### ISSUE THREAD

**Issue by vt-tom** [theripper93/Combat-Booster#13]
Hello im Playing Das Schwarze Auge/The Dark Eye (5th Edition) - Version 3.2.0 and try to configure the Lifepoints to mark an Actor as defeated. But every value i try to set, isnt working.
If i search for the values with _token.actor.data i find them under data.status.wounds.
I tried data.data.satus.wounds.value and data.status.wounds.value, but nothing works.

I have to say, that in the System, an actor counts as "defeated" if the Lifepoints go unter 0, but they can be below it.

Can you help me somehow to get this working?

**Comment by theripper93** [comment]
i don't know all systems, but does inputing that data path in the console give you a number? also do you get any errors? Your best bet would be to ask in your system channel in the main foundry discord
