### ISSUE TITLE
Error "k is not defined" when updating (1.9.2)

### ISSUE THREAD

**Issue by thejoester** [theripper93/Combat-Booster#15]
Updating my modules I get the error "[k is not defined](https://i.imgur.com/32RQdlf.png)"

Currently on v1.9.2
foundry version 9 build 269

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
