### ISSUE TITLE
Combat Booster Dropping Console Error

### ISSUE THREAD

**Issue by gendokun** [theripper93/Combat-Booster#17]
![grafik](https://user-images.githubusercontent.com/37953318/189232367-b32f4f2b-00cc-4cd0-9a8a-169aa6d5a3bd.png)
Any impact to functionality ? Was not yet able to test a full group play.

**Comment by theripper93** [comment]
V9? V10? Are you using a custom image?

**Comment by gendokun** [comment]
V10 - sorry, yes

**Comment by gendokun** [comment]
Ah sorry, you can close it. the custom image path was lost, or better the image was not there anymore Oo! 
Thanks!!
