### ISSUE TITLE
[Feature Request] Add a hook that fires when recent actions gets updated

### ISSUE THREAD

**Issue by Krigsmaskine** [theripper93/Combat-Booster#20]
Hi,

This is mostly related to the many questions I've been asking you on the Discord as well; it'd be helpful for manipulating the recent actions list, if it fired a hook when it's finished with its' normal run, since it has a hardcoded delay/timeout. I understand this is for a bug fix, so I'm not asking to remove that, but can a hook be added and fired when it's done? That way our macros can latch onto it. Thanks for your time!

**Comment by theripper93** [comment]
You can use the update actor hook that is already present in core foundry

**Comment by Krigsmaskine** [comment]
Due to hardcoded timeout of the refreshing of recent actions, I experience stray update actors are triggered by other modules and without throwing in an extensive hook on/hook off procedure, I can't hit the update actor that CombatBooster hits.

**Comment by theripper93** [comment]
Yes you can, just check if the update data contains the cb flag :)
