### ISSUE TITLE
BUG Midi and Dig down not liking combat booster

### ISSUE THREAD

**Issue by MotoMoto1234** [theripper93/Combat-Booster#24]
The following two errors follow anytime I cast a spell with a template in midiqol.  It happens with midi 29 and 30, but I'm on 29 for reasons unrelated. 

Midiqol 10.0.29(and 30)
dnd5e 2.1.4
foundry build 291
Dig Down 
Combat Booster 3.5.1
Dig Down 2.2

(This error is confirmed to be occurring by multiple midi users and goes away when CB is disabled)

![image](https://user-images.githubusercontent.com/116308065/220445790-97574669-4171-4788-b9a4-575683f54389.png)

**Comment by theripper93** [comment]
I have all 3 modules enabled (and dependencies) and i'm not getting this error

**Comment by theripper93** [comment]
I have no idea of the cause of this issue, but i've added a try catch block so that the error is handled and does not stop the workflow in the event it happens
