### ISSUE TITLE
rollItemMacro has been deprecated in dnd5e 2.2

### ISSUE THREAD

**Issue by maqloner** [theripper93/Combat-Booster#26]
**I have disabled all other modules: **True
**Module(s) **Combat-Booster
**Conflicting Module(s) **
**Foundry and System version **v10, v11
**OS, Hosting, Browser (if applicable) **
**Short description of bug **rollItemMacro has been deprecated in dnd5e 2.2
**Simple steps to reproduce the bug **

dnd5e: https://github.com/foundryvtt/dnd5e/pull/1655/files

The affected code: https://github.com/theripper93/Combat-Booster/blob/873493dd2254275cf826e663db42b7fcf0835119/scripts/CombatHud.js#L68

**Screenshots and/or Console Errors**

**Comment by theripper93** [comment]
fixed
