### ISSUE TITLE
[Feature Request] Move to body pile at the end of the current turn

### ISSUE THREAD

**Issue by GhostwheelX** [theripper93/Combat-Booster#28]
Would it be possible to add an option to move dead NPC tokens to the body pile at the end of the current turn instead of immediately?

There are some (rare) cases where monsters don't die immediately when they reach 0 hp, and being able to do so before having to drag the monster from the monster pile would be handy.

Or perhaps a token-specific option where they aren't moved to the body pile? That would also work well.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
