### ISSUE TITLE
[Feature Request] Allow specific NPCs not to be added to the body pile

### ISSUE THREAD

**Issue by GhostwheelX** [theripper93/Combat-Booster#29]
Would it be possible to allow specific NPCs that are defeated **not** to go to the body pile in the top left?

I love the execution, but there are specific NPCs that I want to stay where they are when they die. Would it be possible to add a checkbox somewhere on the NPC sheet to give the option for them not to go into the body pile?

Alternatively, is there an effect that can be added through DAE that will let them "count" as a player for the purpose of the body pile?

Many thanks!

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
