### ISSUE TITLE
Mark Defeated 

### ISSUE THREAD

**Issue by Ginkgo85** [theripper93/Combat-Booster#30]
Unfortunately, the automatic marking of enemies when they are dead doesn't work for me in The Dark Eye system in V12. It worked great in v11.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
