### ISSUE TITLE
In V9 Body Pile does not work

### ISSUE THREAD

**Issue by Zamrod** [theripper93/Combat-Booster#8]
When a creature is reduced to 0 hitpoints in V9 Test 2 (235) with Combat Booster 1.9 it does not move and it throws the following error:

CombatBooster.js:41 Uncaught (in promise) TypeError: token.update is not a function
[Detected 1 package: combatbooster]
    at CombatBooster.js:41

**Comment by theripper93** [comment]
Ah I must have forgotten a deprecated method , well spotted I’ll get it fixed later today

**Comment by theripper93** [comment]
fixed
