### ISSUE TITLE
[Feature Request] Marker for starting position

### ISSUE THREAD

**Issue by supernovajm** [theripper93/Combat-Booster#9]
I switched to Combat Booster from Turn Marker due to incompatibility with v.0.9.0. The one feature I miss is having a marker that indicates where the token was at the beginning of their turn. Any possibility of having this added?

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
